### PR TITLE
Multi profile

### PR DESCRIPTION
**Pull request by stipo42**
Updated project to allow users to configure multiple repositories and pick which to use with existing IntelliVault actions.

This offers a great enhancement for a realistic AEM development experience, where a user would likely be running an author and publish instance at the same time.

### CODE REVIEW

**Comment by shsteimer** [comment]
I like this idea, and it looks promising, should have a chance to review in more detail later today.

**Review by shsteimer — APPROVED** [review]
this is good stuff.  a few quibbles that I'll fix before releasing, but overall I like it.

**Comment by stipo42** [comment]
Awesome, thanks for merging, the one thing I couldn't figure out is how to get the dialog selection window to remember the last-chosen repository. 
Probably could have gotten it with more time but I needed to use what I had (We're doing some heavy AEM development at my place of work)

**Comment by stipo42** [comment]
Hey there, it has been a while, just wondering how this is going? I'd like to share this with some newer co-workers and it'd be cool to just point them to the official IntelliVault plugin from IntelliJ instead of having them build from the source.

**Pull request merged**
